name = "cf-ai-research-paper-finder"
main = "src/index.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "RESEARCH_AGENT"
class_name = "ResearchAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ResearchAgent"]

[ai]
binding = "AI"
